# Generated by Django 4.1.5 on 2023-01-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=50, verbose_name='Quem?')),
                ('tarefa', models.CharField(max_length=100, verbose_name='O que?')),
                ('data', models.DateField(verbose_name='Quando?')),
                ('status', models.CharField(choices=[('Fechado', 'Fechado'), ('Pendente', 'Pendente'), ('Em Progresso', 'Em Progresso')], max_length=20, verbose_name='Status')),
            ],
        ),
    ]
