# Generated by Django 4.1.5 on 2023-01-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pessoas_cargo_pessoas_setor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoas',
            options={'ordering': ['nome'], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['-data'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.RemoveField(
            model_name='pessoas',
            name='setor',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='setor',
            field=models.CharField(choices=[('Produção', 'Produção'), ('Financeiro', 'Financeiro'), ('Logística', 'Logística'), ('Engenharia', 'Engenharia'), ('Manutenção', 'Manutenção'), ('Administração', 'Administração'), ('Recursos Humanos', 'Recursos Humanos')], default='Outros', max_length=50, verbose_name='Setor'),
        ),
    ]
