# Generated by Django 4.1.5 on 2023-01-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_tarefa_setor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['-data'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Feito', 'Feito'), ('Em Progresso', 'Em Progresso'), ('Pendente', 'Pendente')], max_length=20, verbose_name='Status'),
        ),
    ]
